### ISSUE TITLE
关于background 属性无法复制到微信求解

### ISSUE THREAD

**Issue by Ran-Xing** [didadi599/wechat-markdown-editor#2]
```css
/*
  所有定制样式写在 .paper 选择器下
  .paper 类是包裹元素
  设置 code 标签需要用到 .paper .code-inline
*/
.paper {
    padding: 1.6rem;
    color: #333;
    font-size: 14px;
    background: #FC5C7D;
    /* fallback for old browsers */
    background: -webkit-linear-gradient(to bottom, #6A82FB, #FC5C7D);
    /* Chrome 10-25, Safari 5.1-6 */
    background: linear-gradient(to bottom, #6A82FB, #FC5C7D);
    /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */

}

.paper * {
    box-sizing: border-box
}



.paper hr {
    margin-top: 20px;
    margin-bottom: 20px;
    border: 0;
    border-top: 1px solid #eee
}

.paper strong {
    font-weight: 700
}

.paper a {
    color: #428bca;
    text-decoration: none;
    background: 0 0
}

.paper p {
    margin: 10px 0;
    line-height: 1.7
}

.paper p {
    line-height: 1.75;
    font-family: -apple-system-font, BlinkMacSystemFont, Helvetica Neue, PingFang SC, Hiragino Sans GB, Microsoft YaHei UI, Microsoft YaHei, Arial, sans-serif;
    font-size: 14px;
    font-style: normal;
    border-left: none;
    padding: 1em;
    border-radius: 8px;
    color: rgba(0, 0, 0, 0.5);
    background: rgb(255 255 255 / 45%);
    backdrop-filter: blur(14px) saturate(150%);
}

.paper h1,
.paper h2,
.paper h3 {
    margin-top: 20px;
    margin-bottom: 10px
}

.paper h1,
.paper h2,
.paper h3,
.paper h4,
.paper h5,
.paper h6 {
    font-family: inherit;
    font-weight: 500;
    line-height: 1.1;
    color: inherit
}

.paper h1 {
    font-size: 36px
}

.paper h2 {
    text-align: center;
    line-height: 1.75;
    font-family: -apple-system-font, BlinkMacSystemFont, Helvetica Neue, PingFang SC, Hiragino Sans GB, Microsoft YaHei UI, Microsoft YaHei, Arial, sans-serif;
    font-size: 1.2em;
    font-weight: bold;
    display: table;
    padding: 0 0.3em;
    background: rgba(0, 152, 116, 1);
    color: #fff;
    margin-top: 0;
}

.paper h3 {

    text-align: center;
    line-height: 1.75;
    font-family: -apple-system-font, BlinkMacSystemFont, Helvetica Neue, PingFang SC, Hiragino Sans GB, Microsoft YaHei UI, Microsoft YaHei, Arial, sans-serif;
    font-size: 1em;
    font-weight: bold;
    display: table;
    padding: 0 0.3em;
    background: rgba(250, 81, 81, 1);
    color: #fff;
    margin-top: 0;
}

.paper h4 {
    font-size: 18px
}

.paper h5 {
    font-size: 14px
}

.paper h6 {
    font-size: 12px
}

.paper blockquote {
    margin-top: -10px;
    margin-bottom: 10px text-align: left;
    line-height: 1.75;
    font-family: -apple-system-font, BlinkMacSystemFont, Helvetica Neue, PingFang SC, Hiragino Sans GB, Microsoft YaHei UI, Microsoft YaHei, Arial, sans-serif;
    font-size: 14px;
    font-style: normal;
    border-left: none;
    border-radius: 8px;
    color: rgba(0, 0, 0, 0.5);
    margin: 2em 8px;
    backdrop-filter: blur(14px) saturate(150%);
}

.paper .code-inline {
    padding: 2px 4px;
    font-size: 90%;
    color: #c7254e;
    background-color: #f9f2f4;
    border-radius: 4px
}

.paper .code-block {
    display: block;
    padding: 9.5px;
    margin: 0 0 10px;
    font-size: 13px;
    line-height: 1.42857143;
    color: #333;
    word-break: break-all;
    word-wrap: break-word;
    background-color: #f5f5f5;
    border: 1px solid #ccc;
    border-radius: 4px
}

.paper .hljs {
    border-radius: 4px
}

.paper table {
    width: 100%;
    max-width: 100%;
    margin-bottom: 20px;
    border-spacing: 0
}

.paper table>thead:first-child>tr:first-child>th {
    border-top: 0
}

.paper th {
    vertical-align: bottom;
    border-bottom: 2px solid #ddd;
    padding: 8px;
    line-height: 1.42857143;
    text-align: left;
    word-break: normal
}

.paper tr:nth-child(odd) td {
    background-color: #f9f9f9
}

.paper td {
    padding: 8px;
    line-height: 1.42857143;
    vertical-align: top;
    border-top: 1px solid #ddd
}

.paper img {
    max-width: 35%;
    vertical-align: middle
}

.paper mark {
    padding: .2em;
    background-color: #fcf8e3
}

.paper dt {
    font-weight: 700
}

.paper dd {
    margin-left: 0
}

.paper dd,
.paper dt {
    line-height: 1.42857143
}

.paper abbr[title] {
    cursor: help;
    border-bottom: 1px dotted #777
}

.paper .tips {
    background-color: #f3f5f7;
    border-color: #42b983;
    padding: .1rem 1.5rem;
    border-left-width: .5rem;
    border-left-style: solid;
    margin: 1rem 0
}

.paper .tips .tips-title {
    font-weight: 600;
    margin-bottom: -.4rem
}

.paper .footnotes {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    -moz-column-count: 2;
    -webkit-column-count: 2;
    column-count: 2
}

.paper .footnotes-list {
    padding-left: 2em
}

.paper ol,
.paper ul {
    line-height: 1.75;
    font-family: -apple-system-font, BlinkMacSystemFont, Helvetica Neue, PingFang SC, Hiragino Sans GB, Microsoft YaHei UI, Microsoft YaHei, Arial, sans-serif;
    font-size: 14px;
    font-style: normal;
    border-left: none;
    padding: 1em;
    padding-left: 2em;
    border-radius: 8px;
    color: rgba(0, 0, 0, 0.5);
    background: rgb(255 255 255 / 45%);
    margin: 2em 8px;
    backdrop-filter: blur(14px) saturate(150%);
}
```
